### ISSUE TITLE
Lack of Rounded Corners on One Button's Side

### ISSUE THREAD

**Issue by SarahDowling** [SarahDowling/project-1#1]
Navigation buttons are all rounded except last one, I can't seem to figure out what's causing the lack of rounded corners on the right side. I was thinking it was padding or margins pushing it, but I can't see where it is. Any help would be appreciated!

I've included screenshots of what it looks like in chrome, and any CSS code that I think could be causing it. Let me know if you would need anything else to assist.

Link to webpage: http://sarahdowling.github.io/project-1/

@thomasjbradley

```
nav{
    text-align: center;
    padding-bottom: 0.5em;
}

nav li{
    display: inline;
    background-color: #b2a215;
    padding: 0.5em 0;
    border-radius: 5px;
    margin-bottom: 0.75em;
    font-size: 1.2rem
}

nav li a{
    display: inline-block;
    color: white;
    text-decoration: none;
    padding: 0.5em 0.25em;
}

nav li:hover{
    background-color:#b32f52;
}


ol{
    list-style-type: none;
    margin: 0;
    padding: 0;
    display: inline-block;
}

```

![issue at 320p](https://cloud.githubusercontent.com/assets/10464616/6094480/67b2e2a6-aef9-11e4-8b7f-2f98015e523d.png)
![issue at 600p](https://cloud.githubusercontent.com/assets/10464616/6094481/67b5181e-aef9-11e4-934d-d0e82cb7a884.png)

**Comment by thomasjbradley** [comment]
On the `ol` do we want it to take up only as much space as it needs or should it fill one whole line?

**Comment by SarahDowling** [comment]
I thought I tried that already, but it appears to have worked now. Thanks!
